### ISSUE TITLE
"ValueError: negative dimensions are not allowed" and suggested fix

### ISSUE THREAD

**Issue by Bronnnn** [ECOWET-Toolset/Pymonics#1]
Hello, 
i just got the error message  "ValueError: negative dimensions are not allowed", 
when running the comprehensive example.

To fix it i had to change "Pymonics/pymonics/Memo_esprit.py"
line 48: inputDataSamples = inputSignal.iloc[0, :]
to: inputDataSamples = inputSignal.iloc[:, 0]

I am new to github and programming, so sorry if i disregarded some conventions.

**Comment by venkat0249** [comment]
Dear @Bronnnn Thanks for posting here. I tried to run the comprehensive example on my machine. I didn't receive any such error. Could you provide more details of the error? Also, if you are interested to collaborate and contribute to this package, feel free to approach us. We can add you to contributor list.
